/**
 * Mock Data
 * Used in Phase 3–6 while the backend is not yet connected.
 * In Phase 9 these will be replaced by real Axios API calls.
 */

export const MOCK_DESTINATIONS = [
  { _id: '1', name: 'Goa', country: 'India', packageCount: 12, image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400' },
  { _id: '2', name: 'Manali', country: 'India', packageCount: 9, image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=400' },
  { _id: '3', name: 'Kerala', country: 'India', packageCount: 14, image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=400' },
  { _id: '4', name: 'Rajasthan', country: 'India', packageCount: 11, image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=400' },
  { _id: '5', name: 'Kashmir', country: 'India', packageCount: 8, image: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=400' },
  { _id: '6', name: 'Andaman', country: 'India', packageCount: 7, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400' },
];

export const MOCK_PACKAGES = [
  {
    _id: 'p1',
    name: 'Goa Beach Paradise',
    destination: 'Goa',
    description: 'Experience the pristine beaches of Goa with this all-inclusive 5-day package. Enjoy water sports, nightlife, and authentic Goan cuisine.',
    price: 18500,
    duration: 5,
    rating: 4.5,
    reviewCount: 128,
    maxTravelers: 20,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600',
      'https://images.unsplash.com/photo-1563449503831-9f2dae0e6a5b?w=600',
    ],
    includedServices: ['Hotel Stay', 'Breakfast & Dinner', 'Airport Transfers', 'Sightseeing', 'Tour Guide'],
    excludedServices: ['Flights', 'Lunch', 'Personal Expenses', 'Travel Insurance'],
    itinerary: [
      { day: 1, title: 'Arrival & Check-in', description: 'Arrive at Goa airport, transfer to hotel, evening beach walk.' },
      { day: 2, title: 'North Goa Beaches', description: 'Visit Baga, Calangute, and Anjuna beaches. Water sports activities.' },
      { day: 3, title: 'Old Goa Heritage', description: 'Explore Basilica of Bom Jesus, Se Cathedral, and Fontainhas.' },
      { day: 4, title: 'South Goa & Spice Farm', description: 'Visit Palolem beach, spice plantation tour, traditional lunch.' },
      { day: 5, title: 'Departure', description: 'Morning leisure, checkout, transfer to airport.' },
    ],
    availableDates: ['2026-09-15', '2026-10-05', '2026-10-20', '2026-11-10'],
  },
  {
    _id: 'p2',
    name: 'Manali Snow Adventure',
    destination: 'Manali',
    description: 'Thrill-packed 6-day adventure in the snow-capped Himalayas. Skiing, snow trekking, and breathtaking mountain views await you.',
    price: 24000,
    duration: 6,
    rating: 4.7,
    reviewCount: 95,
    maxTravelers: 15,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600',
      'https://images.unsplash.com/photo-1571919014647-3b8c9b5f1f8e?w=600',
    ],
    includedServices: ['Hotel Stay', 'All Meals', 'Ski Equipment', 'Airport Transfers', 'Tour Guide'],
    excludedServices: ['Flights', 'Personal Expenses', 'Adventure Activity Insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Manali', description: 'Arrive, check-in, acclimatization walk in Mall Road.' },
      { day: 2, title: 'Solang Valley', description: 'Snow activities, skiing lessons for beginners, snowboarding.' },
      { day: 3, title: 'Rohtang Pass', description: 'Drive to Rohtang (permit required), snow play, scenic views.' },
      { day: 4, title: 'Kullu River Rafting', description: 'White water rafting on Beas River, Kullu market visit.' },
      { day: 5, title: 'Hadimba Temple & Vashisht', description: 'Local temple visit, hot springs at Vashisht, Old Manali.' },
      { day: 6, title: 'Departure', description: 'Checkout and transfer to Bhuntar airport/bus stand.' },
    ],
    availableDates: ['2026-09-20', '2026-10-10', '2026-11-05'],
  },
  {
    _id: 'p3',
    name: 'Kerala Backwaters Bliss',
    destination: 'Kerala',
    description: 'Glide through the serene backwaters of Alleppey on a houseboat, explore tea gardens of Munnar, and unwind on pristine beaches.',
    price: 22000,
    duration: 7,
    rating: 4.8,
    reviewCount: 210,
    maxTravelers: 12,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600',
    ],
    includedServices: ['Houseboat Stay', 'Hotel Stay', 'All Meals', 'Transfers', 'Ayurveda Session'],
    excludedServices: ['Flights', 'Personal Expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Kochi', description: 'Arrive at Cochin airport, check-in, Fort Kochi evening walk.' },
      { day: 2, title: 'Munnar Tea Gardens', description: 'Drive to Munnar, tea plantation tour, visit Mattupetty Dam.' },
      { day: 3, title: 'Munnar Sightseeing', description: 'Eravikulam National Park, Top Station, Echo Point.' },
      { day: 4, title: 'Thekkady', description: 'Periyar Wildlife Sanctuary boat ride, spice garden tour.' },
      { day: 5, title: 'Alleppey Houseboat', description: 'Board houseboat, cruise through backwaters, overnight stay.' },
      { day: 6, title: 'Kovalam Beach', description: 'Drive to Kovalam, beach leisure, Ayurveda massage.' },
      { day: 7, title: 'Departure from Trivandrum', description: 'Morning checkout, transfer to airport.' },
    ],
    availableDates: ['2026-09-25', '2026-10-15', '2026-11-20'],
  },
  {
    _id: 'p4',
    name: 'Rajasthan Royal Tour',
    destination: 'Rajasthan',
    description: 'Live like royalty on this grand 8-day tour of the Golden Triangle plus Jodhpur and Udaipur. Palaces, forts, and camel rides.',
    price: 32000,
    duration: 8,
    rating: 4.6,
    reviewCount: 175,
    maxTravelers: 25,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600',
    ],
    includedServices: ['Palace Hotel Stay', 'Breakfast', 'AC Coach', 'Guide', 'Camel Ride'],
    excludedServices: ['Flights', 'Lunch & Dinner', 'Entry Fees'],
    itinerary: [
      { day: 1, title: 'Jaipur Arrival', description: 'Check-in, evening at Chokhi Dhani.' },
      { day: 2, title: 'Pink City', description: 'Amber Fort, Hawa Mahal, City Palace, Jantar Mantar.' },
      { day: 3, title: 'Jaipur to Jodhpur', description: 'Drive, visit Mehrangarh Fort, Jaswant Thada.' },
      { day: 4, title: 'Blue City', description: 'Umaid Bhawan, clock tower market, camel ride in desert.' },
      { day: 5, title: 'Jodhpur to Udaipur', description: 'En-route Ranakpur Jain temple visit.' },
      { day: 6, title: 'Lake City Udaipur', description: 'City Palace, Pichola Lake boat ride, Saheliyon ki Bari.' },
      { day: 7, title: 'Pushkar', description: 'Brahma temple, Pushkar Lake, local market.' },
      { day: 8, title: 'Departure', description: 'Transfer to Jaipur airport/railway station.' },
    ],
    availableDates: ['2026-10-01', '2026-10-25', '2026-11-15'],
  },
  {
    _id: 'p5',
    name: 'Andaman Island Escape',
    destination: 'Andaman',
    description: 'Crystal clear waters, white sand beaches, and world-class snorkeling. A paradise 6-day getaway in the Andaman Islands.',
    price: 28500,
    duration: 6,
    rating: 4.9,
    reviewCount: 88,
    maxTravelers: 16,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
    ],
    includedServices: ['Resort Stay', 'Breakfast & Dinner', 'Snorkeling Gear', 'Ferry Transfers', 'Guide'],
    excludedServices: ['Flights to Port Blair', 'Scuba Diving', 'Personal Expenses'],
    itinerary: [
      { day: 1, title: 'Port Blair Arrival', description: 'Arrive, check-in, visit Cellular Jail and Light & Sound show.' },
      { day: 2, title: 'Havelock Island', description: 'Ferry to Havelock, Radhanagar Beach (Asia\'s Best Beach).' },
      { day: 3, title: 'Elephant Beach', description: 'Snorkeling, glass bottom boat ride, beach leisure.' },
      { day: 4, title: 'Neil Island', description: 'Ferry to Neil, Bharatpur Beach, Laxmanpur Beach sunset.' },
      { day: 5, title: 'Back to Port Blair', description: 'Chidiya Tapu (bird watching), Ross Island, Marina Park.' },
      { day: 6, title: 'Departure', description: 'Transfer to Port Blair airport.' },
    ],
    availableDates: ['2026-09-10', '2026-10-08', '2026-11-01'],
  },
  {
    _id: 'p6',
    name: 'Kashmir Valley Dream',
    destination: 'Kashmir',
    description: 'Shikara rides on Dal Lake, Mughal gardens, and the breathtaking beauty of Gulmarg and Pahalgam.',
    price: 26000,
    duration: 6,
    rating: 4.7,
    reviewCount: 142,
    maxTravelers: 18,
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600',
    ],
    includedServices: ['Houseboat Stay', 'Hotel Stay', 'All Meals', 'Shikara Ride', 'Transfers'],
    excludedServices: ['Flights', 'Gondola Ride', 'Personal Expenses'],
    itinerary: [
      { day: 1, title: 'Srinagar Arrival', description: 'Check into houseboat on Dal Lake, Shikara ride at sunset.' },
      { day: 2, title: 'Mughal Gardens', description: 'Nishat Bagh, Shalimar Bagh, Chashme Shahi, local market.' },
      { day: 3, title: 'Gulmarg', description: 'Drive to Gulmarg, Gondola ride, snow activities, meadows.' },
      { day: 4, title: 'Pahalgam', description: 'Beautiful Lidder River valley, Betaab Valley, Aru Valley.' },
      { day: 5, title: 'Sonmarg', description: 'Thajiwas Glacier, river trout fishing, scenic drive.' },
      { day: 6, title: 'Departure', description: 'Morning Shikara ride, transfer to airport.' },
    ],
    availableDates: ['2026-09-05', '2026-10-12', '2026-11-28'],
  },
];

export const MOCK_REVIEWS = [
  { _id: 'r1', user: { name: 'Priya Sharma', avatar: null }, rating: 5, comment: 'Absolutely amazing trip! Everything was well-organized and the guide was fantastic.', createdAt: '2025-10-15' },
  { _id: 'r2', user: { name: 'Rahul Verma', avatar: null }, rating: 4, comment: 'Great experience overall. The hotels were comfortable and food was excellent.', createdAt: '2025-09-22' },
  { _id: 'r3', user: { name: 'Anita Patel', avatar: null }, rating: 5, comment: 'Best vacation of my life! Will definitely book again.', createdAt: '2025-11-01' },
];

export const MOCK_COUPONS = [
  { _id: 'c1', code: 'TRIP20', discountType: 'percentage', discountValue: 20, minimumAmount: 15000, maximumDiscount: 5000, expiryDate: '2027-12-31', status: 'active', usedCount: 42 },
  { _id: 'c2', code: 'SAVE500', discountType: 'fixed', discountValue: 500, minimumAmount: 5000, maximumDiscount: 500, expiryDate: '2027-12-31', status: 'active', usedCount: 18 },
  { _id: 'c3', code: 'NEWUSER', discountType: 'percentage', discountValue: 15, minimumAmount: 10000, maximumDiscount: 3000, expiryDate: '2027-12-31', status: 'active', usedCount: 7 },
];
